"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

type Template = { id: string; name: string; marketplace: string; categoryId: string | null; categoryName: string | null; defaultAttributes: unknown; defaultVatRate: number | null; defaultCargoCompanyId: number | null; defaultDeliveryDuration: number | null; defaultBrandId: number | null };
const empty = { name: "", marketplace: "trendyol", categoryId: "", categoryName: "", defaultAttributes: "{}", defaultVatRate: "", defaultCargoCompanyId: "", defaultDeliveryDuration: "", defaultBrandId: "" };
export default function TemplateManager({ templates }: { templates: Template[] }) {
  const router = useRouter(); const [form, setForm] = useState<Record<string, string>>(empty); const [editing, setEditing] = useState<string | null>(null);
  function edit(template: Template) { setEditing(template.id); setForm({ ...Object.fromEntries(Object.keys(empty).map((key) => [key, String(template[key as keyof Template] ?? "")])), defaultAttributes: JSON.stringify(template.defaultAttributes ?? {}, null, 2) }); }
  async function save(event: React.FormEvent) { event.preventDefault(); try { const payload = { ...form, defaultAttributes: JSON.parse(form.defaultAttributes || "{}") }; const response = await fetch(editing ? `/api/product-templates/${editing}` : "/api/product-templates", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error ?? "Save failed"); toast.success("Template saved"); setEditing(null); setForm(empty); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Save failed"); } }
  async function remove(id: string) { const response = await fetch(`/api/product-templates/${id}`, { method: "DELETE" }); if (!response.ok) return toast.error("Delete failed"); router.refresh(); }
  const fields = [["name", "Ad"], ["categoryId", "Kategori Kimliği"], ["categoryName", "Kategori Adı"], ["defaultVatRate", "Varsayılan KDV"], ["defaultCargoCompanyId", "Kargo Firması Kimliği"], ["defaultDeliveryDuration", "Teslimat Süresi"], ["defaultBrandId", "Marka Kimliği"]] as const;
  return <><section className="rounded-[28px] border bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">Product templates</h1><form onSubmit={save} className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-sm">Marketplace<select value={form.marketplace} onChange={(e) => setForm({ ...form, marketplace: e.target.value })} className="mt-2 w-full rounded-xl border px-3 py-2"><option value="trendyol">Trendyol</option><option value="shopify">Shopify</option></select></label>{fields.map(([key, label]) => <label key={key} className="text-sm">{label}<input required={key === "name"} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-2 w-full rounded-xl border px-3 py-2" /></label>)}<label className="text-sm md:col-span-3">Default attributes JSON<textarea rows={5} value={form.defaultAttributes} onChange={(e) => setForm({ ...form, defaultAttributes: e.target.value })} className="mt-2 w-full rounded-xl border px-3 py-2 font-mono text-xs" /></label><div className="flex gap-2"><button className="rounded-xl bg-gray-900 px-4 py-2 text-sm font-semibold text-white">{editing ? "Update" : "Create"}</button>{editing ? <button type="button" onClick={() => { setEditing(null); setForm(empty); }} className="rounded-xl border px-4 py-2 text-sm">Cancel</button> : null}</div></form></section><section className="overflow-x-auto rounded-[28px] border bg-white shadow-sm"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-gray-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Marketplace</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">VAT</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{templates.map((template) => <tr key={template.id} className="border-t"><td className="px-4 py-3">{template.name}</td><td className="px-4 py-3">{template.marketplace}</td><td className="px-4 py-3">{template.categoryName ?? template.categoryId ?? "-"}</td><td className="px-4 py-3">{template.defaultVatRate ?? "-"}</td><td className="px-4 py-3"><button onClick={() => edit(template)} className="mr-2 rounded-lg border px-3 py-2">Edit</button><button onClick={() => void remove(template.id)} className="rounded-lg border border-rose-200 px-3 py-2 text-rose-700">Delete</button></td></tr>)}</tbody></table></section></>;
}
