import { PageHeader, StatCard } from "@/components/ui";
import { db } from "@/lib/db";
import { buildProductReadiness } from "@/lib/product-readiness";
export default async function ReadinessPage() {
  const [products, mappings, categories, brands] = await Promise.all([db.product.findMany({ include: { images: { orderBy: { sortOrder: "asc" } } } }), db.categoryMapping.findMany({ where: { marketplace: "trendyol" } }), db.marketplaceCategoryCache.findMany({ where: { marketplace: "trendyol" }, select: { externalId: true, name: true } }), db.marketplaceBrandCache.findMany({ where: { marketplace: "trendyol" }, select: { externalId: true, name: true } })]);
  const results = products.map((p) => buildProductReadiness(p, mappings, { categories, brands }).readiness);
  const shopifyReady = results.filter((r) => r.shopify.ready).length; const trendyolReady = results.filter((r) => r.trendyol.ready).length;
  const problems = [["Eksik barkod", "barcode"], ["Eksik kategori", "categoryId"], ["Eksik marka", "brandId"], ["Eksik görsel", "images"]].map(([label, field]) => ({ label, count: results.filter((r) => r.trendyol.missingFields.includes(field)).length }));
  return <main className="px-4 py-8 md:px-8"><div className="mx-auto max-w-7xl space-y-6"><PageHeader title="Hazırlık Durumu" description="Tüm ürünlerin dışa aktarım engellerini ve eksik bilgilerini toplu olarak inceleyin." /><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><StatCard label="Toplam Ürün" value={products.length} /><StatCard label="Shopify Hazır" value={shopifyReady} /><StatCard label="Shopify Eksik Bilgili" value={products.length - shopifyReady} /><StatCard label="Trendyol Hazır" value={trendyolReady} /><StatCard label="Trendyol Eksik Bilgili" value={products.length - trendyolReady} /></section><section className="rounded-[28px] border bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Yaygın Eksikler</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{problems.map((p) => <div key={p.label} className="flex items-center justify-between rounded-xl bg-gray-50 p-4"><span className="text-sm font-medium">{p.label}</span><span className="text-xl font-bold">{p.count}</span></div>)}</div></section></div></main>;
}
